### ISSUE TITLE
Handle bad gzip body

### ISSUE THREAD

**Issue by chulkilee** [chulkilee/ex_force#10]
Could not reproduced it, but anyway ExForce needs to handle bad gzip body.

```
** (ErlangError) Erlang error: :data_error
    :zlib.inflateEnd_nif(#Reference<0.2868773574.1493303297.176518>)
    :zlib.gunzip/1
    (ex_force) lib/ex_force/client.ex:51: ExForce.Client.gunzip/1
    (ex_force) lib/ex_force/client.ex:32: ExForce.Client.request!/5
    (ex_force) lib/ex_force.ex:216: ExForce.query_retrieve/2
    (ex_force) lib/ex_force.ex:281: ExForce.stream_unfold/1
```

**Comment by chulkilee** [comment]
Are there any other having this issue? I'm seeing this error so added `IO.inspect` before unzip, and the problem is gone! :(

**Comment by chulkilee** [comment]
Not seeing this error anymore. Closing it.
